// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH-Pqxcei4rr3lkce06G65HcaO5Lw9oN0',
    appId: '1:162261285833:web:b2e68f81d04b3891154618',
    messagingSenderId: '162261285833',
    projectId: 'barcodedelivery-437a6',
    authDomain: 'barcodedelivery-437a6.firebaseapp.com',
    storageBucket: 'barcodedelivery-437a6.appspot.com',
    measurementId: 'G-TQV3RZV6HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB8-dJx-rrBX_TIh5donlQIFaCgJCTZfQ',
    appId: '1:162261285833:android:643f73500ec55d64154618',
    messagingSenderId: '162261285833',
    projectId: 'barcodedelivery-437a6',
    storageBucket: 'barcodedelivery-437a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPYh7GhbdqNdb7e9yO2r62hOBiAwig4iY',
    appId: '1:162261285833:ios:b29f325575309114154618',
    messagingSenderId: '162261285833',
    projectId: 'barcodedelivery-437a6',
    storageBucket: 'barcodedelivery-437a6.appspot.com',
    iosBundleId: 'com.example.foodPandasFoodDeliveryAppWithBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPYh7GhbdqNdb7e9yO2r62hOBiAwig4iY',
    appId: '1:162261285833:ios:b29f325575309114154618',
    messagingSenderId: '162261285833',
    projectId: 'barcodedelivery-437a6',
    storageBucket: 'barcodedelivery-437a6.appspot.com',
    iosBundleId: 'com.example.foodPandasFoodDeliveryAppWithBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH-Pqxcei4rr3lkce06G65HcaO5Lw9oN0',
    appId: '1:162261285833:web:bbf4f79c8858dc8c154618',
    messagingSenderId: '162261285833',
    projectId: 'barcodedelivery-437a6',
    authDomain: 'barcodedelivery-437a6.firebaseapp.com',
    storageBucket: 'barcodedelivery-437a6.appspot.com',
    measurementId: 'G-YXVVTB482M',
  );
}
